#!/bin/bash

#this script starts all of the local services needed while developing cash analytics

cd ~/work/cashanalytics
gnome-terminal --tab --title="Cashanalytics: rails s" -e "bash -c 'rails s'" --tab-with-profile=Default --title="Delayed Job" -e "bash -c 'rake jobs:work'" --tab-with-profile=Default --title="Console" -e "bash -c 'rails c'" --tab-with-profile=Default --title="Use me!"
gnome-terminal --tab --title="Cashanalytics: Guard" -e "bash -c 'guard'"

#TODO: open pgadmin
#TODO: open Chrome and run lvh.me:3000
#TODO: open cashanalytics Sublime Folder
#TODO: choose which screen to open on
#TODO: maximise all windows as they are opened
#TODO: close all so that can run similar file for another project

